In [3]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)
mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jillian Claire's Array: [55 47 12 17 53 47 24  2 34 52]
Mean: 34.3 Std Dev: 18.330575550156627


In [4]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jillian Claire's Matrix:
 [[12 17 24  2]
 [34 11 13 21]
 [13 14 26 30]]
Row sums: [55 79 83]
Column sums: [59 42 63 53]


In [6]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)
slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)


Jillian Claire's 3D Array:
 [[[22 14 11]
  [16 20 14]
  [23  1  1]]

 [[19 19 10]
  [12 24 23]
  [13 20 19]]

 [[12 13  6]
  [10  3  3]
  [ 5  9 17]]]
Slice[:,1,:]:
 [[16 20 14]
 [12 24 23]
 [10  3  3]]


In [8]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Jillian Claire's Original: [55 47 12 17 53 47 24  2 34 52]
Filtered subset: []


In [9]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)
product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[12 17]
 [24  2]]
Matrix B:
 [[34 11]
 [13 21]]
A @ B:
 [[629 489]
 [842 306]]
Determinant of A: -384.0


In [10]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jillian Claire's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [11]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Jillian Claire's Modified 4x4 Array:
 [[ 0 17  0  2]
 [34 11 13 21]
 [ 0 14  0 30]
 [11  4  6 18]]


In [12]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)


Jillian Claire's Scores: [54 33 51 55 45 51 25 57 38 35]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [13]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[12 17 24  2]
 [34 11 13 21]
 [13 14 26 30]]
Flattened: [12 17 24  2 34 11 13 21 13 14 26 30]
Transposed:
 [[12 34 13]
 [17 11 14]
 [24 13 26]
 [ 2 21 30]]


In [14]:
import numpy as np
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 17 -1]
 [-1 -1 11]
 [13 21 13]]


In [17]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)


             Name  Score  YearsCodePro
0  Jillian Claire     61             1
1  Jillian Claire     26             1
2  Jillian Claire     31            19
3  Jillian Claire     61            19
4  Jillian Claire     38            10


In [16]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    66371.0
Master      85489.0
PhD         64139.0
Name: ConvertedComp, dtype: float64


In [18]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
4      Germany         125620
3       Canada          72848
2           UK          64139
0  Philippines          59894
1          USA          45358


In [19]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

             Name  YearsCodePro
0  Jillian Claire            22
1  Jillian Claire            14
2  Jillian Claire            11
3  Jillian Claire            16
4  Jillian Claire            20


In [20]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)


   ConvertedComp   Bracket
0          59894   50-100k
1          45358     0-50k
2          64139   50-100k
3          72848   50-100k
4         125620  100-150k


In [21]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)


   ConvertedComp    LogComp
0          59894  11.000332
1          45358  10.722342
2          64139  11.068808
3          72848  11.196130
4         125620  11.741017


In [22]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro        1.00000        0.64057
ConvertedComp       0.64057        1.00000


In [26]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)


    EdLevel     mean   median           std
0  Bachelor  66371.0  66371.0   9159.861243
1    Master  85489.0  85489.0  56753.804472
2       PhD  64139.0  64139.0           NaN


In [27]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
threshold = 110000
# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          59894      No
1          45358      No
2          64139      No
3          72848      No
4         125620     Yes


In [29]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Jillian Claire"
STUDENT_ID = 715
np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        72848.0   72848
Germany      125620.0  125620
Philippines   59894.0   59894
UK            64139.0   64139
USA           45358.0   45358
